[kafka_ex]
brokers = "travis:9092"

[core."Core.Repo"]
database = "mpi_dev"
username = "postgres"
password = "postgres"
hostname = "travis"
port = 5432

[person_updates_producer."PersonUpdatesProducer.Worker"]
batch_size = 100
